os:
  - osx
  - linux
language: generic
sudo: required

services:
  - docker

before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew

install: scripts/travis-setup.sh

script: scripts/travis-run.sh

env:
  global:
    - SUBDAGS=1
    - BIOCONDA_UTILS_TAG=master
    - BIOCONDA_UTILS_BUILD_ARGS="--loglevel=info"
    - BIOCONDA_UTILS_LINT_ARGS=
    - MINICONDA_VER="4.2.12"
  matrix:
    - SUBDAG=0

matrix:
  fast_finish: true
