install: scripts/travis-setup.sh

script: scripts/travis-run.sh

env:
  global:
    - SUBDAGS=1
    - BIOCONDA_UTILS_TAG=isolated-conda
    - BIOCONDA_UTILS_BUILD_ARGS="--loglevel=info"
    - BIOCONDA_UTILS_LINT_ARGS=
    - MINICONDA_VER="4.2.12"
  matrix:
    - SUBDAG=0

matrix:
  fast_finish: true
  include:
    - os: osx
      language: generic
    - os: linux
      sudo: required
      python: "3.6"
      services:
        - docker
