{% set version = "2.9.3" %}
{% set sha256 = "c2dc6897fe7599d04e1af32a08d86c3eb28ab7fb268ca2165c03d6ff2b3744e8" %}

package:
  name: ariba
  version: {{ version }}

source:
  fn: ariba-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/a/ariba/ariba-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True # [py27]
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - dendropy >=4.1.0
    - pyfastaq >=3.12.0
    - pysam >=0.9.1
    - pymummer >=0.10.2
    - matplotlib
    - gcc  # [not osx]
    - llvm  # [osx]
    - zlib

  run:
    - python
    - dendropy >=4.1.0
    - pyfastaq >=3.12.0
    - pysam >=0.9.1
    - pymummer >=0.10.2
    - matplotlib
    - bowtie2 >=2.1.0
    - cd-hit >=4.6
    - samtools >=1.2
    - bcftools >=1.2
    - mummer >=3.23
    - spades >=3.5.0
    - libgcc  # [not osx]
    - zlib

test:
  imports:
    - ariba
    - ariba.tasks

  requires:
    - nose >=1.3

about:
  home: https://github.com/sanger-pathogens/ariba
  license: GNU General Public License v3 (GPLv3)
  summary: 'ARIBA: Antibiotic Resistance Identification By Assembly'
