{% set name = "flexidot" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a9f52b8a2556a6cc63dba343272f06e24edf225279c985f4f792fc8050e920d0

build:
  run_exports:
    - {{ pin_subpackage('flexidot', max_pin="x.x") }}
  entry_points:
    - flexidot = flexidot.app:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-vcs
    - pip
  run:
    - "biopython"
    - "colormap"
    - "colour"
    - "easydev"
    - "matplotlib-base"
    - "numpy"
    - "regex"
    - "rich"

test:
  imports:
    - flexidot
  commands:
    - pip check
    - flexidot --help
  requires:
    - pip

about:
  home: https://github.com/flexidot-bio/flexidot
  summary: Flexible dotplotting of genomic sequences.
  license: GNU Lesser General Public License v3 (LGPLv3)
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Adamtaranto
