package:
  name: transrate
  version: "1.0.3"

build:
  skip: True  #[osx]
  number: 0
  string: {{PKG_BUILDNUM}}

source:
  fn: transrate-1.0.3.tar.gz
  url: https://github.com/blahah/transrate/archive/v1.0.3.tar.gz
  md5: d17cc8f4420d9b1778b3843f142b0dd9

requirements:
  build:
    - gcc >=4.8
    - libgcc
    - bamtools
    - zlib
    - cmake
    - make
    - gnu-wget
    - transrate-tools
    - salmon
    - blast
    - snap-aligner
    - ruby >=2.1.7,<=2.1.7

  run:
    - libgcc
    - bamtools
    - zlib
    - transrate-tools
    - salmon
    - blast
    - snap-aligner
    - ruby >=2.1.7,<=2.1.7

test:
  commands:
     - transrate 2>&1 | grep "by Richard Smith-Unna" > /dev/null

about:
  home: https://github.com/blahah/transrate
  license: MIT
  license_file: LICENSE
  summary: Command-line tools used by transrate for processing bam files.

extra:
  recipe-maintainers:
    - notestaff

